#!/bin/bash
#	FORMAT BOOTABLE USB

#	Run as root user
#	Find USB Device Path
fdisk -l

iso=CentOS-7-x86_64-Minimal-1611.iso
usb=/dev/sdb
part1=/dev/sdb1
part2=/dev/sdb2

# 	Create Two Partitions
fdisk /dev/sdX

n (create partition, accept defaults for type, number, and first sector)
+250M (defined size as 250MB)
t
c (change type to W95 FAT32 (LBA) - other FAT types may work, but I have not tried)
a (make bootable)
n (create partition, accept defaults for type, number, first sector, and size)
w (write changes to device)

# 	Format partitons
mkfs -t vfat -n "BOOT" /dev/sdb1
mkfs -L "DATA" /dev/sdb2

#	Write MBR data to device
yum install syslinux
dd conv=notrunc bs=440 count=1 if=/usr/share/syslinux/mbr.bin of=/dev/sdb

#	Install syslinux to first parition
syslinux /dev/sdb1

#	Mount the partitions
mkdir -p /BOOT && mount /dev/sdb1 BOOT
mkdir -p /DATA && mount /dev/sdb2 DATA
mkdir -p /DVD && mount /CentOS-7-x86_64-Minimal-1611.iso DVD
cp /DVD/isolinux/* /BOOT
mv /BOOT/isolinux.cfg /BOOT/syslinux.cfg
cp /CentOS-7-x86_64-Minimal-1611.iso /DATA
